update to subvolumes
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>

diff --git a/bin/pmos-adopt-and-integrate b/bin/pmos-adopt-and-integrate
--- a/bin/pmos-adopt-and-integrate
+++ b/bin/pmos-adopt-and-integrate
@@ -1,6 +1,18 @@
 #!/bin/sh
 
-cp -ax /pmos/boot/ /
-cp -ax /pmos/lib/modules/ /lib/
-cp -ax /pmos/lib/firmware/ /lib/
-cp -ax /pmos/usr/share/alsa/ucm2/ /usr/share/alsa/
+if [ "$#" -eq 0 ]; then
+  SRC=/sda17p2/pmos
+  DST=/sda17p2/fedora
+elif [ "$#" -eq 2 ]; then
+  SRC="${1}"; shift
+  DST="${1}"; shift
+else
+  echo "cannot detect source and destination" 2>&1
+  exit 1
+fi
+
+cp -ax "${SRC}"/boot/ "${DST}"/
+cp -ax "${SRC}"/lib/modules/ "${DST}"/lib/
+cp -ax "${SRC}"/lib/firmware/ "${DST}"/lib/
+cp -ax "${SRC}"/usr/share/alsa/ucm2/ "${DST}"/usr/share/alsa/
+
